### PR TITLE
Start global chain fee module

### LINKED ISSUE #7: Add consensus min_fee for gas
Cosmos has an interesting idea to allow validators to quickly adjust the block gas by making it subjective - each validator sets the required gas to enter a block their produce. While it is quite flexible to allow responding to spam (raising min gas quickly and temporarily based on off-chain social coordination), it does a poor job providing a stable baseline for running the chain.  Many validators forget and leave 0 gas. Trying to convince everyone to set a similar value is quite difficult (outside of an emergency).

We should add an "AnteHandler" that enforces a min-gas fee, which can be set in genesis and adjusted by governance proposals.

### PR DESCRIPTION
**Pull request by alpe**
Resolves #7 

New module with ante handler and genesis IO to enforce global minimum gas price(s)

### CODE REVIEW

**Comment by robert-zaremba** [comment]
I think you should us `v1` for your proto version.

**Comment by ethanfrey** [comment]
We try to stay consistent with the cosmos-sdk.

Why is [bank still on v1beta1](https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/bank/v1beta1/bank.proto)?

**Comment by robert-zaremba** [comment]
Because 0.1 was not possible and we weren't sure how this will evolve.
Personally i think it should have been called V1 from the beginning.
I master this is changing now to v1.

**Comment by ethanfrey** [comment]
We will make the update once the pain of changing has been handled by the Cosmos SDK team. This is client api breaking and a big headache. 

We still use Cosmos SDK 0.45 and will handle the renaming with the 0.46 update. We are also 1 week from tgrade launch and not about to rename all proto.... this is not meant for consumption by cosmos-sdk:main/0.46.x yet

**Pull request merged**
